from setuptools import setup, Extension
from Cython.Build import cythonize

setup(
    ext_modules=cythonize(Extension(
        name="trial",  # Name of the resulting shared object/DLL
        sources=["trial.c"],  # Your C file generated by Cython
    )),
)
